#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成中文 16x16 点阵字库头文件 (src/cn_font.h)

用法: python tools/gen_font.py
自动扫描 src/ 下 .cpp/.h 源文件中出现的所有 CJK 字符,
从 Windows 系统中文字体(SimHei/SimSun/微软雅黑)渲染为 16x16 位图,
输出为 C 头文件,供 TFT_eSPI 显示中文。

依赖: pillow  (pip install pillow)
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
OUT = os.path.join(SRC, "cn_font.h")

FONT_CANDIDATES = [
    r"C:\Windows\Fonts\simhei.ttf",
    r"C:\Windows\Fonts\msyh.ttc",
    r"C:\Windows\Fonts\simsun.ttc",
]

SIZE = 16          # 字模尺寸
THRESHOLD = 100    # 灰度阈值


def collect_chars():
    chars = set()
    for fn in sorted(os.listdir(SRC)):
        if not (fn.endswith(".cpp") or fn.endswith(".h")):
            continue
        if fn == "cn_font.h":
            continue
        path = os.path.join(SRC, fn)
        try:
            text = open(path, encoding="utf-8").read()
        except Exception as e:
            print("skip", fn, e)
            continue
        for ch in text:
            cp = ord(ch)
            if 0x4E00 <= cp <= 0x9FFF:
                chars.add(ch)
            elif cp > 0x7F:
                print(f"  [warn] 非CJK字符 {ch!r} U+{cp:04X} 出现在 {fn},已忽略")
    return sorted(chars)


def find_font():
    for p in FONT_CANDIDATES:
        if os.path.exists(p):
            return p
    raise SystemExit("未找到中文字体,请安装 SimHei 或修改 FONT_CANDIDATES")


def render_glyph(font, ch):
    from PIL import Image, ImageDraw
    img = Image.new("L", (SIZE, SIZE), 0)
    d = ImageDraw.Draw(img)
    bbox = font.getbbox(ch)
    w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    x = (SIZE - w) // 2 - bbox[0]
    y = (SIZE - h) // 2 - bbox[1]
    d.text((x, y), ch, font=font, fill=255)
    px = img.load()
    out = bytearray()
    for row in range(SIZE):
        b = 0
        for col in range(SIZE):
            if px[col, row] > THRESHOLD:
                b |= (0x8000 >> col)
        out.append((b >> 8) & 0xFF)
        out.append(b & 0xFF)
    return bytes(out)


def utf8_key(ch):
    b = ch.encode("utf-8")
    return (b[0] << 16) | (b[1] << 8) | b[2]


def main():
    from PIL import ImageFont
    chars = collect_chars()
    if not chars:
        print("未找到任何中文字符,请确认源码中存在中文 UI 字符串")
        return 1
    print(f"共 {len(chars)} 个字符")

    font_path = find_font()
    font = ImageFont.truetype(font_path, SIZE)
    glyphs = [render_glyph(font, ch) for ch in chars]

    lines = [
        "/* Generated by tools/gen_font.py -- do not edit manually */",
        "#ifndef CN_FONT_H",
        "#define CN_FONT_H",
        "#include <stdint.h>",
        f"#define CN_FONT_COUNT {len(chars)}",
        f"#define CN_FONT_CELL_W {SIZE}",
        f"#define CN_FONT_CELL_H {SIZE}",
        f"#define CN_FONT_BYTES {SIZE * 2}",
        "static const uint32_t cn_keys[CN_FONT_COUNT] = {",
    ]
    lines += ["    " + ", ".join(f"0x{k:06X}" for k in map(utf8_key, chars)) + "};"]
    lines.append("static const uint8_t cn_glyphs[CN_FONT_COUNT * CN_FONT_BYTES] = {")
    for i in range(0, len(glyphs), 8):
        chunk = glyphs[i:i + 8]
        row = ", ".join("0x%02X" % b for g in chunk for b in g)
        lines.append("    " + row + ",")
    lines += ["};", "#endif // CN_FONT_H", ""]

    open(OUT, "w", encoding="utf-8").write("\n".join(lines))
    print(f"已生成 {OUT}  ({len(chars)} 字符, {len(chars) * SIZE * 2} 字节)")


if __name__ == "__main__":
    sys.exit(main())
